version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: node:14.18.1-alpine
    steps:
      - checkout
      - run: npm install
      - setup_remote_docker
      - run:
          name: Install curl
          command: apk update && apk add curl curl-dev bash
      - run:
          name: Install Docker Compose
          command: |
            set -x
            - curl -L https://github.com/docker/compose/releases/download/1.10.0/docker-compose-`uname -s`-`uname -m` > /home/ubuntu/bin/docker-compose
            - chmod +x /home/ubuntu/bin/docker-compose
            - docker-compose version
      - run:
          name: Start all services declared in docker-compose.yml
          command: |
            set -x
            docker-compose up -d
      - run: npm run test:unit