version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: node:14.18.1-alpine
    steps:
      - checkout
      - run: npm install
      - setup_remote_docker
      - run:
          name: Start all services declared in docker-compose.yml
          command: docker-compose up -d
      - run: npm run test:unit